# yaml-language-server: $schema=https://squidfunk.github.io/mkdocs-material/schema.json

INHERIT: base.yml

plugins:
  - search
  - glightbox
  - awesome-pages
  - offline
  - social:
      cards_layout_options:
        font_family: Red Hat Display
  - charts
  - git-committers:
      repository: twangodev/wisc
      branch: main
      token: !ENV ["MKDOCS_GIT_COMMITTERS_APIKEY"]
  - git-revision-date-localized:
      enable_creation_date: true
  - rss:
      length: -1
  - open-in-new-tab
  - print-site:
      toc_depth: 6

extra:
  analytics:
    provider: custom