name: Build and Deploy Documentation

on:
  workflow_dispatch:
  push:

env:
  MKDOCS_GIT_COMMITTERS_APIKEY: ${{ secrets.MKDOCS_GIT_COMMITTERS_APIKEY }}

concurrency:
  group: build-and-deploy-${{ github.ref }}
  cancel-in-progress: false

jobs:

  run-sync:
    name: Run Sync Script
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: 3
          cache: pipenv

      - name: Install pipenv
        run: python3 -m pip install --upgrade pip pipenv

      - name: Install Dependencies
        run: pipenv sync

      - name: Run Python Script
        run: pipenv run python course_details.py

      - name: Run Python Script and Check for Changes
        id: check_changes
        run: git diff --exit-code || echo "files_changed=true" >> $GITHUB_OUTPUT
        continue-on-error: true

      - name: Commit Changes
        if: steps.check_changes.outputs.files_changed == 'true'
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Auto-update from script"
          branch: ${{ github.ref_name }}

  build:
    name: Build MkDocs
    runs-on: ubuntu-latest
    environment: production
    needs: run-sync
    if: needs.run-sync.outputs.files_changed != 'true'
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v4
        with:
          python-version: 3
          cache: pipenv
      - name: Install pipenv
        run: python3 -m pip install --upgrade pip pipenv
      - name: Install Dependencies
        run: pipenv sync
      - name: Restore Build Cache
        uses: actions/cache/restore@v4
        with:
          key: mkdocs-material-${{ hashfiles('.cache/**') }}
          path: .cache
          restore-keys: |
            mkdocs-material-
      - name: Build Documentation
        run: pipenv run mkdocs build
      - name: Upload Pages Artifact
        uses: actions/upload-pages-artifact@v3
        if: github.ref == 'refs/heads/main'
        with:
          path: site
      - name: Save Build Cache
        uses: actions/cache/save@v4
        with:
          key: mkdocs-material-${{ hashfiles('.cache/**') }}
          path: .cache

  deploy:
    name: Deploy MkDocs
    needs: build
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4